

library(shiny)
library(shinythemes)
library(DT)


fluidPage(theme = shinytheme("cerulean"),
          tags$head(tags$style(".shiny-notification {position: fixed; top: 40%;left: 50%")),
          # section below allows in-line LaTeX via $ in mathjax.
          tags$div(HTML("<script type='text/x-mathjax-config' >
            MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$','$']]}
            });
            </script >
            ")),
        navbarPage("Navigation Tabs",
                   tabPanel("About",
                            mainPanel(
                                h1("Welcome to my Housing App!", align="center"),
                                div(tags$img(src="house.png", 
                                             height="60%", 
                                             width="60%", 
                                             alt="Something went wrong", 
                                             deleteFile=FALSE),
                                    align="center"),
                                h3("Purpose of this App", align="center"),
                                p("The purpose of this app is to allow users an
                                  interactive, investigative and exploratory 
                                  experience with some housing data, all while 
                                  also avoiding the need to know how to code in 
                                  R. The user should be able to adjust or 
                                  customize all of the inputs for the code 
                                  running on the backend through simple and easy 
                                  to understand widgets, effectively simplifying 
                                  the barrier between the user and the analysis."),
                                h3("Data Source", align="center"),
                                p("The data used on this shiny application comes
                                   from the user 'Ashish' on Kaggle and provides
                                   the characteristics of 545 different homes ranging
                                   from the number of bedrooms and bathrooms to
                                   the furnished status of the home. The data
                                   contains a total of 13 variables, where the
                                   singular sale price variable will be used as
                                   the target response and the other 12 will be
                                   used as predictors. Unfortunately, there was
                                   not a proper file provided on the meta data
                                   so it is not clear which country the houses
                                   are based in or the currency of the sale price,
                                   but for the purposes of this app, we will assume
                                   that these are houses from the United States
                                   and the currency is USD."),
                                uiOutput("tab", align="center"),
                                h3("Purpose of Tabs", align="center"),
                                p("This app is organized into 4 pages so that
                                  the user can move through each step of the 
                                  analysis. Currently, we are on the about
                                  page. This page is to give users a chance to
                                  be introduced to the app and provide an intution
                                  into the data source. The next page over is 
                                  dedicated to allow the user to explore the data.
                                  
                                  COME BACK TO THIS
                                  
                                  
                                  ",
                                  align="center"),
                                br(),
                                width=12
                            )
                   ),
                   tabPanel("Data Exploration",
                            tabsetPanel(
                              tabPanel("Graphs",
                                       sidebarLayout(
                                         sidebarPanel(h2("Select a Graph or Summary"),
                                           radioButtons("typeOfGraph", 
                                                        "Which Type of Graph or Summary Would Like to See?",
                                                        c("A Histogram of a Single Numeric Variable" = "hist",
                                                          "A Piechart of a Single Categorical Variable" = "pie",
                                                          "A Scatter Plot of Two Numerical Variables" = "scatter",
                                                          "A Bar Plot of the Average Value of a Numeric Variable 
                                                          by a Categorical Variable" = "bar",
                                                          "A Boxplot of a Numerical Variable by a Categorical 
                                                          Variable" = "box"),
                                                        selected = character(0)),
                                           conditionalPanel(condition = "input.typeOfGraph == 'hist'",
                                                            radioButtons("typeOfHistogram", 
                                                                         "Which Numeric Variable Should Be Used?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            numericInput("numBins",
                                                                         label="Select the Number of Bins",
                                                                         value=30, min=0, max=100,
                                                                         step=5),
                                                            radioButtons("histogramSubset", 
                                                                        "Should the Values of the Numeric Variable be Subsetted?",
                                                                        c("Yes" = "yes",
                                                                          "No" = "no"),
                                                                        selected = "no"),
                                                            conditionalPanel(condition = "input.histogramSubset == 'yes'",
                                                                             numericInput("lowRangeHist",
                                                                                          "Choose a Minimum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRangeHist",
                                                                                          "Choose a Maximum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 15))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'pie'",
                                                            radioButtons("typeOfPiechart", 
                                                                         "Which Categorical Variable Should Be Used?",
                                                                         c("Mainroad" = "mainroad",
                                                                           "Guestroom" = "guestroom",
                                                                           "Basement" = "basement",
                                                                           "HotWaterHeating" = "hotwaterheating",
                                                                           "Airconditioning" = "airconditioning",
                                                                           "PreferredArea" = "prefarea",
                                                                           "FurnishingStatus" = "furnishingstatus"),
                                                                         selected = character(0))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'scatter'",
                                                            radioButtons("yScatter", 
                                                                         "Which Numeric Variable Should Be on the Y Axis?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            radioButtons("xScatter", 
                                                                         "Which Numeric Variable Should Be on the X Axis?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            radioButtons("scatterSubset", 
                                                                         "Should the Values of the Numeric Variables be Subsetted?",
                                                                         c("Yes" = "yes",
                                                                           "No" = "no"),
                                                                         selected = "no"),
                                                            conditionalPanel(condition = "input.scatterSubset == 'yes'",
                                                                             numericInput("lowRangeScatter1",
                                                                                          "Choose a Minimum for the Numeric 
                                                                                          Variable on the Y Axis:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRangeScatter1",
                                                                                          "Choose a Maximum for the Numeric 
                                                                                          Variable on the Y Axis:",
                                                                                          min = 0, max = 15000000, value = 15),
                                                                             numericInput("lowRangeScatter2",
                                                                                          "Choose a Minimum for the Numeric 
                                                                                          Variable on the X Axis:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRangeScatter2",
                                                                                          "Choose a Maximum for the Numeric 
                                                                                          Variable on the X Axis:",
                                                                                          min = 0, max = 15000000, value = 15))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'bar'",
                                                            radioButtons("typeOfBarplotNum", 
                                                                         "Which Numeric Variable Should Be Used?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            radioButtons("typeOfBarplotCat", 
                                                                         "Which Categorical Variable Should Be Used?",
                                                                         c("Mainroad" = "mainroad",
                                                                           "Guestroom" = "guestroom",
                                                                           "Basement" = "basement",
                                                                           "HotWaterHeating" = "hotwaterheating",
                                                                           "Airconditioning" = "airconditioning",
                                                                           "PreferredArea" = "prefarea",
                                                                           "FurnishingStatus" = "furnishingstatus"),
                                                                         selected = character(0)),
                                                            radioButtons("barplotSubset", 
                                                                         "Should the Values of the Numeric Variable be Subsetted?",
                                                                         c("Yes" = "yes",
                                                                           "No" = "no"),
                                                                         selected = "no"),
                                                            conditionalPanel(condition = "input.barplotSubset == 'yes'",
                                                                             numericInput("lowRangeBar",
                                                                                          "Choose a Minimum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRangeBar",
                                                                                          "Choose a Maximum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 15))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'box'",
                                                            radioButtons("typeOfBoxplotNum", 
                                                                         "Which Numeric Variable Should Be Used?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            radioButtons("typeOfBoxplotCat", 
                                                                         "Which Categorical Variable Should Be Used?",
                                                                         c("Mainroad" = "mainroad",
                                                                           "Guestroom" = "guestroom",
                                                                           "Basement" = "basement",
                                                                           "HotWaterHeating" = "hotwaterheating",
                                                                           "Airconditioning" = "airconditioning",
                                                                           "PreferredArea" = "prefarea",
                                                                           "FurnishingStatus" = "furnishingstatus"),
                                                                         selected = character(0)),
                                                            radioButtons("boxplotSubset", 
                                                                         "Should the Values of the Numeric Variable be Subsetted?",
                                                                         c("Yes" = "yes",
                                                                           "No" = "no"),
                                                                         selected = "no"),
                                                            conditionalPanel(condition = "input.boxplotSubset == 'yes'",
                                                                             numericInput("lowRangeBox",
                                                                                          "Choose a Minimum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRangeBox",
                                                                                          "Choose a Maximum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 15))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'contingency'",
                                                            radioButtons("typeOfContingencyTable", 
                                                                         "How Many Levels Should the Contingency Table Have?",
                                                                         c("One" = "one",
                                                                           "Two" = "two",
                                                                           "Three" = "three"),
                                                                         selected = character(0)),
                                                            conditionalPanel(condition = "input.typeOfContingencyTable == 'one'",
                                                                             radioButtons("singleCatVar", 
                                                                                          "Which Categorical Variable Should Be Used?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0))),
                                                            conditionalPanel(condition = "input.typeOfContingencyTable == 'two'",
                                                                             radioButtons("doubleCatVar1", 
                                                                                          "Which Categorical Variable Should 
                                                                                          Be Used for the First Level?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0)),
                                                                             radioButtons("doubleCatVar2", 
                                                                                          "Which Categorical Variable Should 
                                                                                          Be Used for the Second Level?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0))),
                                                            conditionalPanel(condition = "input.typeOfContingencyTable == 'three'",
                                                                             radioButtons("tripleCatVar1", 
                                                                                          "Which Categorical Variable Should 
                                                                                          Be Used for the First Level?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0)),
                                                                             radioButtons("tripleCatVar2", 
                                                                                          "Which Categorical Variable Should 
                                                                                          Be Used for the Second Level?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0)),
                                                                             radioButtons("tripleCatVar3", 
                                                                                          "Which Categorical Variable Should 
                                                                                          Be Used for the Third Level?",
                                                                                          c("Mainroad" = "mainroad",
                                                                                            "Guestroom" = "guestroom",
                                                                                            "Basement" = "basement",
                                                                                            "HotWaterHeating" = "hotwaterheating",
                                                                                            "Airconditioning" = "airconditioning",
                                                                                            "PreferredArea" = "prefarea",
                                                                                            "FurnishingStatus" = "furnishingstatus"),
                                                                                          selected = character(0)))),
                                           conditionalPanel(condition = "input.typeOfGraph == 'summary'",
                                                            radioButtons("typeOfSummary", 
                                                                         "Which Numeric Variable Should Be Used?",
                                                                         c("Price" = "price",
                                                                           "Area" = "area",
                                                                           "Bedrooms" = "bedrooms",
                                                                           "Bathrooms" = "bathrooms",
                                                                           "Stories" = "stories",
                                                                           "Parking" = "parking"),
                                                                         selected = character(0)),
                                                            radioButtons("summarySubset", 
                                                                         "Should the Values of the Numeric Variable be Subsetted?",
                                                                         c("Yes" = "yes",
                                                                           "No" = "no"),
                                                                         selected = "no"),
                                                            conditionalPanel(condition = "input.summarySubset == 'yes'",
                                                                             numericInput("lowRange",
                                                                                          "Choose a Minimum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 1),
                                                                             numericInput("highRange",
                                                                                          "Choose a Maximum for the Numeric Variable:",
                                                                                          min = 0, max = 15000000, value = 15))),
                                           br(),
                                           actionButton("runGraph", strong("Create Graph/Summary"),style = "color: #428bca;")
                                           
                                           
                                           
                                           
                                                            
                                
                              ),
                              mainPanel(
                                uiOutput("text_header5"),
                                br(),
                                uiOutput("subtext_header7"),
                                plotOutput("finalPlot"),
                                verbatimTextOutput("finalSum")
                                
                              )
                            )
                   ),
                   tabPanel("Modeling",
                            tabsetPanel(
                              tabPanel("Modeling Info",
                                       sidebarLayout(
                                         sidebarPanel(
                                           h2(strong("Model Choice")),
                                           br(),
                                           radioButtons("modelTypeInfo", 
                                                        "Which Model Would You Like to Learn More About?",
                                                        c("Multiple Linear Regression Model" = "aboutMLR",
                                                          "Bagged Tree Regression Model" = "aboutBT",
                                                          "Random Forest Model" = "aboutRF"),
                                                        selected = character(0))
                                           
                                         ),
                                         mainPanel(
                                           uiOutput("text_header4"),
                                           br(),
                                           uiOutput("subtext_header4"),
                                           uiOutput("paragraph1"),
                                           uiOutput("modelMath"),
                                           uiOutput("subtext_header5"),
                                           uiOutput("paragraph2"),
                                           uiOutput("subtext_header6"),
                                           uiOutput("paragraph3"),
                                           br(),
                                           br()
                                
                                         )
                                       )
                              ),
                              tabPanel("Model Fitting",
                                       sidebarLayout(
                                         sidebarPanel(
                                           numericInput("trainSplit",
                                                  label="Select Training Split Proportion",
                                                  value=.75, min=0, max=1,
                                                  step=.05),
                                           numericInput("testSplit",
                                                  label="Select Testing Split Proportion",
                                                  value=.25, min=0, max=1,
                                                  step=.05),
                                           h4(strong("Multiple Linear Regression Model"), style = "color:red;"),
                                           radioButtons("mlrVariables", 
                                                              "What Variables Should be Included?",
                                                              c("All Variables" = "all",
                                                                "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.mlrVariables.includes('custom')",
                                           checkboxGroupInput("mlrCustom", 
                                                              "Variables Used in Model:",
                                                              c("Area" = "area",
                                                                "Bedrooms" = "bedrooms",
                                                                "Bathrooms" = "bathrooms",
                                                                "Stories" = "stories",
                                                                "Mainroad" = "mainroad",
                                                                "Guestroom" = "guestroom",
                                                                "Basement" = "basement",
                                                                "HotWaterHeating" = "hotwaterheating",
                                                                "Airconditioning" = "airconditioning",
                                                                "Parking" = "parking",
                                                                "PreferredArea" = "prefarea",
                                                                "FurnishingStatus" = "furnishingstatus"),
                                                              selected = "area")),
                                           checkboxInput("mlrInteractions",
                                                         "Interactions among all variables considered"),
                                           numericInput("mlrCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           h4(strong("Bagged Tree Regression Model"), style = "color:red;"),
                                           radioButtons("treeVariables", 
                                                        "What Variables Should be Included?",
                                                        c("All Variables" = "all",
                                                          "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.treeVariables.includes('custom')",
                                                            checkboxGroupInput("treeCustom", 
                                                                               "Variables Used in Model:",
                                                                               c("Area" = "area",
                                                                                 "Bedrooms" = "bedrooms",
                                                                                 "Bathrooms" = "bathrooms",
                                                                                 "Stories" = "stories",
                                                                                 "Mainroad" = "mainroad",
                                                                                 "Guestroom" = "guestroom",
                                                                                 "Basement" = "basement",
                                                                                 "HotWaterHeating" = "hotwaterheating",
                                                                                 "Airconditioning" = "airconditioning",
                                                                                 "Parking" = "parking",
                                                                                 "PreferredArea" = "prefarea",
                                                                                 "FurnishingStatus" = "furnishingstatus"),
                                                                               selected = "area")),
                                           numericInput("treeCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           numericInput("treeCvRepeats",
                                                        label="Number of Repeats for Cross Validation",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           h4(strong("Random Forest Model"), style = "color:red;"),
                                           radioButtons("forestVariables", 
                                                        "What Variables Should be Included?",
                                                        c("All Variables" = "all",
                                                          "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.forestVariables.includes('custom')",
                                                            checkboxGroupInput("forestCustom", 
                                                                               "Variables Used in Model:",
                                                                               c("Area" = "area",
                                                                                 "Bedrooms" = "bedrooms",
                                                                                 "Bathrooms" = "bathrooms",
                                                                                 "Stories" = "stories",
                                                                                 "Mainroad" = "mainroad",
                                                                                 "Guestroom" = "guestroom",
                                                                                 "Basement" = "basement",
                                                                                 "HotWaterHeating" = "hotwaterheating",
                                                                                 "Airconditioning" = "airconditioning",
                                                                                 "Parking" = "parking",
                                                                                 "PreferredArea" = "prefarea",
                                                                                 "FurnishingStatus" = "furnishingstatus"),
                                                                               selected = "area")),
                                           numericInput("forestCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           numericInput("forestCvRepeats",
                                                        label="Number of Repeats for Cross Validation",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           br(),
                                           actionButton("runModels", strong("Run Models"),style = "color: #428bca;")
                                         ),
                                         mainPanel(
                                           uiOutput("text_header1"),
                                           br(),
                                           uiOutput("subtext_header1"),
                                           br(),
                                           uiOutput("desc_header1"),
                                           verbatimTextOutput("modelSummary1"),
                                           uiOutput("desc_header2"),
                                           verbatimTextOutput("RMSE1"),
                                           uiOutput("desc_header3"),
                                           verbatimTextOutput("modelSummary2"),
                                           uiOutput("desc_header4"),
                                           verbatimTextOutput("modelSummary3"),
                                           br(),
                                           uiOutput("subtext_header2"),
                                           br(),
                                           uiOutput("desc_header5"),
                                           plotOutput("plot1"),
                                           uiOutput("desc_header6"),
                                           plotOutput("plot2"),
                                           uiOutput("desc_header7"),
                                           plotOutput("plot3"),
                                           br(),
                                           uiOutput("subtext_header3"),
                                           tableOutput("testTable"),
                                           uiOutput("desc_header8"),
                                           br(),
                                           br()
                                         )
                                       )
                              ),
                              tabPanel("Prediction",
                                       sidebarLayout(
                                         sidebarPanel(
                                           h2(strong("Prediction Adjustments")),
                                           br(),
                                           radioButtons("predictModelType", 
                                                        "Which Model Would You Like to Make Predictions With?",
                                                        c("Multiple Linear Regression Model" = "predictWithMLR",
                                                          "Bagged Tree Regression Model" = "predictWithBT",
                                                          "Random Forest Model" = "predictWithRF"),
                                                        selected = character(0)),
                                           conditionalPanel(condition = "input.predictModelType",
                                           h3("House Attributes:"),
                                           numericInput("predictEntryArea",
                                                        label="Area (in Square Ft)",
                                                        value=2000, min=0, max=100000,
                                                        step=1),
                                           numericInput("predictEntryBedrooms",
                                                        label="Number of Bedrooms",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           numericInput("predictEntryBathrooms",
                                                        label="Number of Bathrooms",
                                                        value=2, min=1, max=10,
                                                        step=1),
                                           numericInput("predictEntryStories",
                                                        label="Number of Stories",
                                                        value=1, min=1, max=5,
                                                        step=1),
                                           radioButtons("predictEntryMainroad", 
                                                        "Is the house connected to a mainroad?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryGuestroom", 
                                                        "Is there a guestroom?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryBasement", 
                                                        "Is there a basement?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryHotwaterheating", 
                                                        "Is there a hot water heater?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryAirconditioning", 
                                                        "Is there air conditioning?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           numericInput("predictEntryParking",
                                                        label="Number of Parking Spots",
                                                        value=1, min=0, max=12,
                                                        step=1),
                                           radioButtons("predictEntryPrefarea", 
                                                        "Is the house in a perferred area?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryFurnished", 
                                                        "What is the furnishing status of the home?",
                                                        c("Furnished" = "furnished",
                                                          "Semi-Furnished" = "semi-furnished",
                                                          "Unfurnished" = "unfurnished"))),
                                           br(),
                                           actionButton("getPrediction", strong("Get Prediction"),style = "color: #428bca;")
                                                            
                                                            
                                                            
                                           
                                         ),
                                         mainPanel(
                                           uiOutput("text_header2"),
                                           uiOutput("prediction"),
                                           uiOutput("text_header3")
                                           
                                         )
                                       )
                              )
                            )  
                   ),
                   tabPanel("Data",
                            sidebarLayout(
                              sidebarPanel(
                                h2("Subset Options", align="center"),
                                br(),
                                h3("Subset Columns:"),
                                checkboxGroupInput("columnSubsets", 
                                                   "Which Columns Should be Included?",
                                                   c("Price" = "price",
                                                     "Area" = "area",
                                                     "Bedrooms" = "bedrooms",
                                                     "Bathrooms" = "bathrooms",
                                                     "Stories" = "stories",
                                                     "Mainroad" = "mainroad",
                                                     "Guestroom" = "guestroom",
                                                     "Basement" = "basement",
                                                     "HotWaterHeating" = "hotwaterheating",
                                                     "Airconditioning" = "airconditioning",
                                                     "Parking" = "parking",
                                                     "PreferredArea" = "prefarea",
                                                     "FurnishingStatus" = "furnishingstatus"),
                                                   selected = c("price",
                                                                "area",
                                                                "bedrooms",
                                                                "bathrooms",
                                                                "stories",
                                                                "mainroad",
                                                                "guestroom",
                                                                "basement",
                                                                "hotwaterheating",
                                                                "airconditioning",
                                                                "parking",
                                                                "prefarea",
                                                                "furnishingstatus")),
                                
                                h3("Subset Rows:"),
                                h4("Price Options:"),
                                sliderInput("priceRange",
                                            label = "Choose a range for the price variable", 
                                            min = 1000000, max = 15000000, value = c(1000000,15000000), dragRange=TRUE
                                ),
                                h5("For more a more precise price range, use the inputs below!"),
                                numericInput("lowPriceRange",
                                             "Choose a minimum for the price variable:",
                                             min = 1000000, max = 15000000, value = 1000000),
                                numericInput("highPriceRange",
                                             "Choose a maximum for the price variable:",
                                             min = 1000000, max = 15000000, value = 15000000),
                                h4("Area Options:"),
                                sliderInput("areaRange",
                                  label = "Choose a range for the area variable", 
                                  min = 0, max = 20000, value = c(0,20000), dragRange=TRUE
                                ),
                                h5("For more a more precise area range, use the inputs below!"),
                                numericInput("lowAreaRange",
                                             "Choose a minimum for the area variable:",
                                             min = 0, max = 20000, value = 0),
                                numericInput("highAreaRange",
                                             "Choose a maximum for the area variable:",
                                             min = 0, max = 20000, value = 20000),
                                h4("Options for Bedrooms:"),
                                checkboxGroupInput("bedroomSubset", 
                                                   "Select the interested number of bedrooms:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4",
                                                     "Five" = "5",
                                                     "Six" = "6"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4",
                                                                "5",
                                                                "6")),
                                h4("Options for Bathrooms:"),
                                checkboxGroupInput("bathroomSubset", 
                                                   "Select the interested number of bathrooms:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4")),
                                h4("Options for Stories:"),
                                checkboxGroupInput("storiesSubset", 
                                                   "Select the interested number of stories:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4")),
                                h4("Mainroad Options:"),
                                checkboxGroupInput("mainroadSubset", 
                                                   "Select the whether the house is connected to a mainroad:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Guestroom Options:"),
                                checkboxGroupInput("guestroomSubset", 
                                                   "Select the whether the house has a guestoom:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Basement Options:"),
                                checkboxGroupInput("basementSubset", 
                                                   "Select the whether the house has a basement:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("HotWaterHeating Options:"),
                                checkboxGroupInput("hotWaterHeatingSubset", 
                                                   "Select the whether the house has a hot water heater:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("AirConditioning Options:"),
                                checkboxGroupInput("airConditioningSubset", 
                                                   "Select the whether the house has air conditioning:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Parking Options:"),
                                checkboxGroupInput("parkingSubset", 
                                                   "Select the interested number of parking spaces:",
                                                   c("Zero" = "0",
                                                     "One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3"),
                                                   selected = c("0",
                                                                "1",
                                                                "2",
                                                                "3")),
                                h4("PrefArea Options:"),
                                checkboxGroupInput("prefareaSubset", 
                                                   "Select the whether the house is in a preferred area:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Furnishing Options:"),
                                checkboxGroupInput("furnishedSubset", 
                                                   "Select the interested furnished status:",
                                                   c("Furnished" = "furnished",
                                                     "Semi-Furnished" = "semi-furnished",
                                                     "Unfurnished" = "unfurnished"),
                                                   selected = c("furnished",
                                                                "semi-furnished",
                                                                "unfurnished")),
                                br(),
                                actionButton("subsetData", strong("Subset Data"),style = "color: #428bca;")
                              ),
                              mainPanel(
                                h1("The Housing Dataset", align="center"),
                                h3("Please explore the data below or subset
                                   it with the panel on the left. Don't forget
                                   to click the submit button at the botton 
                                   after making adjustments!"),
                                br(),
                                dataTableOutput("dataTable"),
                                h3("Interested in saving the data? Click the 
                                    download button below!"),
                                downloadButton('downloadCSV',"Download", 
                                               style = "color: #428bca;"),
                                br()
                              )
                            )
                   ),
        fluid=TRUE)
)


