

library(shiny)
library(shinythemes)
library(DT)


fluidPage(theme = shinytheme("cerulean"),
          tags$head(tags$style(".shiny-notification {position: fixed; top: 40%;left: 50%")),
          # section below allows in-line LaTeX via $ in mathjax.
          tags$div(HTML("<script type='text/x-mathjax-config' >
            MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$','$']]}
            });
            </script >
            ")),
        navbarPage("Navigation Tabs",
                   tabPanel("About",
                            mainPanel(
                                h1("Welcome to my Housing App!", align="center"),
                                div(tags$img(src="house.png", 
                                             height="60%", 
                                             width="60%", 
                                             alt="Something went wrong", 
                                             deleteFile=FALSE),
                                    align="center"),
                                h3("Purpose of this App", align="center"),
                                p("The purpose of this app is to allow users an
                                  interactive and exploratory experience with 
                                  some housing data, while also avoiding the need 
                                  to know how to code in R. The user should be able to adjust
                                  or customize all of the inputs for the code running
                                  on the backend through simple and easy to understand
                                  widgets, simplifying the barrier between the 
                                  user and the analysis."),
                                h3("Data Source", align="center"),
                                p("The data has been sourced from Kaggle",
                                  align="center"),
                                uiOutput("tab", align="center"),
                                h3("Purpose of Tabs", align="center"),
                                p("The tabs are to organize this app",
                                  align="center"),
                                br(),
                                width=12
                            )
                   ),
                   tabPanel("Data Exploration",
                            sidebarLayout(
                              sidebarPanel(
                                
                              ),
                              mainPanel(
                                
                              )
                            )
                   ),
                   tabPanel("Modeling",
                            tabsetPanel(
                              tabPanel("Modeling Info",
                                       sidebarLayout(
                                         sidebarPanel(
                                           h2(strong("Model Choice")),
                                           br(),
                                           radioButtons("modelTypeInfo", 
                                                        "Which Model Would You Like to Learn More About?",
                                                        c("Multiple Linear Regression Model" = "aboutMLR",
                                                          "Bagged Tree Regression Model" = "aboutBT",
                                                          "Random Forest Model" = "aboutRF"),
                                                        selected = character(0))
                                           
                                         ),
                                         mainPanel(
                                           uiOutput("text_header4"),
                                           br(),
                                           uiOutput("subtext_header4"),
                                           uiOutput("paragraph1"),
                                           uiOutput("modelMath"),
                                           uiOutput("subtext_header5"),
                                           uiOutput("paragraph2"),
                                           uiOutput("subtext_header6"),
                                           uiOutput("paragraph3"),
                                           br(),
                                           br()
                                
                                         )
                                       )
                              ),
                              tabPanel("Model Fitting",
                                       sidebarLayout(
                                         sidebarPanel(
                                           numericInput("trainSplit",
                                                  label="Select Training Split Proportion",
                                                  value=.75, min=0, max=1,
                                                  step=.05),
                                           numericInput("testSplit",
                                                  label="Select Testing Split Proportion",
                                                  value=.25, min=0, max=1,
                                                  step=.05),
                                           h4(strong("Multiple Linear Regression Model"), style = "color:red;"),
                                           radioButtons("mlrVariables", 
                                                              "What Variables Should be Included?",
                                                              c("All Variables" = "all",
                                                                "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.mlrVariables.includes('custom')",
                                           checkboxGroupInput("mlrCustom", 
                                                              "Variables Used in Model:",
                                                              c("Area" = "area",
                                                                "Bedrooms" = "bedrooms",
                                                                "Bathrooms" = "bathrooms",
                                                                "Stories" = "stories",
                                                                "Mainroad" = "mainroad",
                                                                "Guestroom" = "guestroom",
                                                                "Basement" = "basement",
                                                                "HotWaterHeating" = "hotwaterheating",
                                                                "Airconditioning" = "airconditioning",
                                                                "Parking" = "parking",
                                                                "PreferredArea" = "prefarea",
                                                                "FurnishingStatus" = "furnishingstatus"),
                                                              selected = "area")),
                                           checkboxInput("mlrInteractions",
                                                         "Interactions among all variables considered"),
                                           numericInput("mlrCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           h4(strong("Bagged Tree Regression Model"), style = "color:red;"),
                                           radioButtons("treeVariables", 
                                                        "What Variables Should be Included?",
                                                        c("All Variables" = "all",
                                                          "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.treeVariables.includes('custom')",
                                                            checkboxGroupInput("treeCustom", 
                                                                               "Variables Used in Model:",
                                                                               c("Area" = "area",
                                                                                 "Bedrooms" = "bedrooms",
                                                                                 "Bathrooms" = "bathrooms",
                                                                                 "Stories" = "stories",
                                                                                 "Mainroad" = "mainroad",
                                                                                 "Guestroom" = "guestroom",
                                                                                 "Basement" = "basement",
                                                                                 "HotWaterHeating" = "hotwaterheating",
                                                                                 "Airconditioning" = "airconditioning",
                                                                                 "Parking" = "parking",
                                                                                 "PreferredArea" = "prefarea",
                                                                                 "FurnishingStatus" = "furnishingstatus"),
                                                                               selected = "area")),
                                           numericInput("treeCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           numericInput("treeCvRepeats",
                                                        label="Number of Repeats for Cross Validation",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           h4(strong("Random Forest Model"), style = "color:red;"),
                                           radioButtons("forestVariables", 
                                                        "What Variables Should be Included?",
                                                        c("All Variables" = "all",
                                                          "Custom Subset" = "custom")),
                                           conditionalPanel(condition = "input.forestVariables.includes('custom')",
                                                            checkboxGroupInput("forestCustom", 
                                                                               "Variables Used in Model:",
                                                                               c("Area" = "area",
                                                                                 "Bedrooms" = "bedrooms",
                                                                                 "Bathrooms" = "bathrooms",
                                                                                 "Stories" = "stories",
                                                                                 "Mainroad" = "mainroad",
                                                                                 "Guestroom" = "guestroom",
                                                                                 "Basement" = "basement",
                                                                                 "HotWaterHeating" = "hotwaterheating",
                                                                                 "Airconditioning" = "airconditioning",
                                                                                 "Parking" = "parking",
                                                                                 "PreferredArea" = "prefarea",
                                                                                 "FurnishingStatus" = "furnishingstatus"),
                                                                               selected = "area")),
                                           numericInput("forestCvFold",
                                                        label="Number of Folds for Cross Validation",
                                                        value=5, min=1, max=10,
                                                        step=1),
                                           numericInput("forestCvRepeats",
                                                        label="Number of Repeats for Cross Validation",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           br(),
                                           actionButton("runModels", strong("Run Models"),style = "color: #428bca;")
                                         ),
                                         mainPanel(
                                           uiOutput("text_header1"),
                                           br(),
                                           uiOutput("subtext_header1"),
                                           br(),
                                           uiOutput("desc_header1"),
                                           verbatimTextOutput("modelSummary1"),
                                           uiOutput("desc_header2"),
                                           verbatimTextOutput("RMSE1"),
                                           uiOutput("desc_header3"),
                                           verbatimTextOutput("modelSummary2"),
                                           uiOutput("desc_header4"),
                                           verbatimTextOutput("modelSummary3"),
                                           br(),
                                           uiOutput("subtext_header2"),
                                           br(),
                                           uiOutput("desc_header5"),
                                           plotOutput("plot1"),
                                           uiOutput("desc_header6"),
                                           plotOutput("plot2"),
                                           uiOutput("desc_header7"),
                                           plotOutput("plot3"),
                                           br(),
                                           uiOutput("subtext_header3"),
                                           tableOutput("testTable"),
                                           uiOutput("desc_header8"),
                                           br(),
                                           br()
                                         )
                                       )
                              ),
                              tabPanel("Prediction",
                                       sidebarLayout(
                                         sidebarPanel(
                                           h2(strong("Prediction Adjustments")),
                                           br(),
                                           radioButtons("predictModelType", 
                                                        "Which Model Would You Like to Make Predictions With?",
                                                        c("Multiple Linear Regression Model" = "predictWithMLR",
                                                          "Bagged Tree Regression Model" = "predictWithBT",
                                                          "Random Forest Model" = "predictWithRF"),
                                                        selected = character(0)),
                                           conditionalPanel(condition = "input.predictModelType",
                                           h3("House Attributes:"),
                                           numericInput("predictEntryArea",
                                                        label="Area (in Square Ft)",
                                                        value=2000, min=0, max=100000,
                                                        step=1),
                                           numericInput("predictEntryBedrooms",
                                                        label="Number of Bedrooms",
                                                        value=3, min=1, max=10,
                                                        step=1),
                                           numericInput("predictEntryBathrooms",
                                                        label="Number of Bathrooms",
                                                        value=2, min=1, max=10,
                                                        step=1),
                                           numericInput("predictEntryStories",
                                                        label="Number of Stories",
                                                        value=1, min=1, max=5,
                                                        step=1),
                                           radioButtons("predictEntryMainroad", 
                                                        "Is the house connected to a mainroad?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryGuestroom", 
                                                        "Is there a guestroom?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryBasement", 
                                                        "Is there a basement?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryHotwaterheating", 
                                                        "Is there a hot water heater?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryAirconditioning", 
                                                        "Is there air conditioning?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           numericInput("predictEntryParking",
                                                        label="Number of Parking Spots",
                                                        value=1, min=0, max=12,
                                                        step=1),
                                           radioButtons("predictEntryPrefarea", 
                                                        "Is the house in a perferred area?",
                                                        c("Yes" = "yes",
                                                          "No" = "no")),
                                           radioButtons("predictEntryFurnished", 
                                                        "What is the furnishing status of the home?",
                                                        c("Furnished" = "furnished",
                                                          "Semi-Furnished" = "semi-furnished",
                                                          "Unfurnished" = "unfurnished"))),
                                           br(),
                                           actionButton("getPrediction", strong("Get Prediction"),style = "color: #428bca;")
                                                            
                                                            
                                                            
                                           
                                         ),
                                         mainPanel(
                                           uiOutput("text_header2"),
                                           uiOutput("prediction"),
                                           uiOutput("text_header3")
                                           
                                         )
                                       )
                              )
                            )  
                   ),
                   tabPanel("Data",
                            sidebarLayout(
                              sidebarPanel(
                                h2("Subset Options", align="center"),
                                br(),
                                h3("Subset Columns:"),
                                checkboxGroupInput("columnSubsets", 
                                                   "Which Columns Should be Included?",
                                                   c("Price" = "price",
                                                     "Area" = "area",
                                                     "Bedrooms" = "bedrooms",
                                                     "Bathrooms" = "bathrooms",
                                                     "Stories" = "stories",
                                                     "Mainroad" = "mainroad",
                                                     "Guestroom" = "guestroom",
                                                     "Basement" = "basement",
                                                     "HotWaterHeating" = "hotwaterheating",
                                                     "Airconditioning" = "airconditioning",
                                                     "Parking" = "parking",
                                                     "PreferredArea" = "prefarea",
                                                     "FurnishingStatus" = "furnishingstatus"),
                                                   selected = c("price",
                                                                "area",
                                                                "bedrooms",
                                                                "bathrooms",
                                                                "stories",
                                                                "mainroad",
                                                                "guestroom",
                                                                "basement",
                                                                "hotwaterheating",
                                                                "airconditioning",
                                                                "parking",
                                                                "prefarea",
                                                                "furnishingstatus")),
                                
                                h3("Subset Rows:"),
                                h4("Price Options:"),
                                sliderInput("priceRange",
                                            label = "Choose a range for the price variable", 
                                            min = 1000000, max = 15000000, value = c(1000000,15000000), dragRange=TRUE
                                ),
                                h5("For more a more precise price range, use the inputs below!"),
                                numericInput("lowPriceRange",
                                             "Choose a minimum for the price variable:",
                                             min = 1000000, max = 15000000, value = 1000000),
                                numericInput("highPriceRange",
                                             "Choose a maximum for the price variable:",
                                             min = 1000000, max = 15000000, value = 15000000),
                                h4("Area Options:"),
                                sliderInput("areaRange",
                                  label = "Choose a range for the area variable", 
                                  min = 0, max = 20000, value = c(0,20000), dragRange=TRUE
                                ),
                                h5("For more a more precise area range, use the inputs below!"),
                                numericInput("lowAreaRange",
                                             "Choose a minimum for the area variable:",
                                             min = 0, max = 20000, value = 0),
                                numericInput("highAreaRange",
                                             "Choose a maximum for the area variable:",
                                             min = 0, max = 20000, value = 20000),
                                h4("Options for Bedrooms:"),
                                checkboxGroupInput("bedroomSubset", 
                                                   "Select the interested number of bedrooms:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4",
                                                     "Five" = "5",
                                                     "Six" = "6"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4",
                                                                "5",
                                                                "6")),
                                h4("Options for Bathrooms:"),
                                checkboxGroupInput("bathroomSubset", 
                                                   "Select the interested number of bathrooms:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4")),
                                h4("Options for Stories:"),
                                checkboxGroupInput("storiesSubset", 
                                                   "Select the interested number of stories:",
                                                   c("One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3",
                                                     "Four" = "4"),
                                                   selected = c("1",
                                                                "2",
                                                                "3",
                                                                "4")),
                                h4("Mainroad Options:"),
                                checkboxGroupInput("mainroadSubset", 
                                                   "Select the whether the house is connected to a mainroad:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Guestroom Options:"),
                                checkboxGroupInput("guestroomSubset", 
                                                   "Select the whether the house has a guestoom:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Basement Options:"),
                                checkboxGroupInput("basementSubset", 
                                                   "Select the whether the house has a basement:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("HotWaterHeating Options:"),
                                checkboxGroupInput("hotWaterHeatingSubset", 
                                                   "Select the whether the house has a hot water heater:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("AirConditioning Options:"),
                                checkboxGroupInput("airConditioningSubset", 
                                                   "Select the whether the house has air conditioning:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Parking Options:"),
                                checkboxGroupInput("parkingSubset", 
                                                   "Select the interested number of parking spaces:",
                                                   c("Zero" = "0",
                                                     "One" = "1",
                                                     "Two" = "2",
                                                     "Three" = "3"),
                                                   selected = c("0",
                                                                "1",
                                                                "2",
                                                                "3")),
                                h4("PrefArea Options:"),
                                checkboxGroupInput("prefareaSubset", 
                                                   "Select the whether the house is in a preferred area:",
                                                   c("Yes" = "yes",
                                                     "No" = "no"),
                                                   selected = c("yes",
                                                                "no")),
                                h4("Furnishing Options:"),
                                checkboxGroupInput("furnishedSubset", 
                                                   "Select the interested furnished status:",
                                                   c("Furnished" = "furnished",
                                                     "Semi-Furnished" = "semi-furnished",
                                                     "Unfurnished" = "unfurnished"),
                                                   selected = c("furnished",
                                                                "semi-furnished",
                                                                "unfurnished")),
                                br(),
                                actionButton("subsetData", strong("Subset Data"),style = "color: #428bca;")
                              ),
                              mainPanel(
                                h1("The Housing Dataset", align="center"),
                                h3("Please explore the data below or subset
                                   it with the panel on the left. Don't forget
                                   to click the submit button at the botton 
                                   after making adjustments!"),
                                br(),
                                dataTableOutput("dataTable"),
                                h3("Interested in saving the data? Click the 
                                    download button below!"),
                                downloadButton('downloadCSV',"Download", 
                                               style = "color: #428bca;"),
                                br()
                              )
                            )
                   ),
        fluid=TRUE)
)


